import type { Metadata } from 'next'
import NextAuthProvider from '@/providers/NextAuth'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex items-center flex-col"> 
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}